sudo: required
language: r
cran: https://cran.rstudio.com/
matrix:
  include:
  - os: linux
    dist: trusty
    r: 3.1.3
    cran: http://cran.rstudio.com/
  - os: linux
    dist: trusty
    r: 3.2.5
    cran: http://cran.rstudio.com/
  - os: linux
    dist: trusty
    r: oldrel
  - os: linux
    dist: trusty
    r: release
    r_github_packages:
    - jimhester/covr
    - jimhester/lintr
    after_success:
    - Rscript -e 'covr::coveralls(package_coverage(type = "all", quiet = FALSE)))'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    before_install:
    r_packages:
    - devtools
  - os: osx
    osx_image: xcode9
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
    before_install:
    - Rscript -e 'install.packages("digest", type = "source")'
r_build_args: '--compact-vignettes="gs+qpdf"'
r_check_args: '--as-cran'
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - development
