language: r

sudo: required

cran: http://cran.rstudio.com/

apt_packages:
  - curl
  - latex-xcolor
  - libcurl4-openssl-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - development
