sudo: required
language: r
cran: https://cran.rstudio.com/
matrix:
  include:
  - os: linux
    dist: trusty
    r: 3.1.0
    cran: http://cran.rstudio.com/
  - os: linux
    dist: trusty
    r: 3.2.0
    cran: http://cran.rstudio.com/
  - os: linux
    dist: trusty
    r: 3.3.0
    cran: http://cran.rstudio.com/
  - os: linux
    dist: trusty
    r: 3.4.0
    cran: http://cran.rstudio.com/
  - os: linux
    dist: trusty
    r: oldrel
  - os: linux
    dist: trusty
    r: release
    r_github_packages:
    - jimhester/covr
    - jimhester/lintr
    after_success:
    - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
    - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: trusty
    r: devel
    r_packages:
    - devtools
  - os: osx
    osx_image: xcode9.2
    latex: false
    r_build_args: '--no-build-vignettes'
    r_check_args: '--as-cran --ignore-vignettes --no-examples'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only:
    - master
    - development
