---
title: "fpCompare"
author: "Alex M. Chubaty"
date: '`r format(Sys.Date(), format="%B %d, %Y")`'
output:
  pdf_document:
    number_sections: no
    toc: no
  html_document:
    number_sections: no
    self_contained: yes
    toc: no
bibliography: bibliography.bib
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{fpCompare: reliable comparison of floating point numbers}
  %\VignetteDepends{fpCompare}
  %\VignetteKeyword{floating point numbers, numerical comparisons}
  %\usepackage[utf8]{inputenc}
---

# Reliable comparison of floating point numbers
Comparisons of floating point numbers are problematic due to errors associated with the binary representation of decimal numbers. Computer scientists and programmers are aware of these problems [*.e.g.*, @Goldberg:1991ac] and yet people still use numerical methods which fail to account for floating point errors (this pitfall is the first to be highlighted in the First Circle of "The R Inferno" [@Burns:2012ri]).

To avoid these and other numerical rounding issues, R's help file for relational operators (*e.g.*, `?'>'`) suggests using `identical` and `all.equal` when making numerical comparisons:

```r
x1 <- 0.5 - 0.3
x2 <- 0.3 - 0.1
x1 == x2                           # FALSE on most machines
identical(all.equal(x1, x2), TRUE) # TRUE everywhere
```

Inspired by [R FAQ 7.31](http://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f) and [this Stack Overflow answer](http://stackoverflow.com/a/2769618/1380598), this package provides new relational operators useful for performing floating point number comparisons with a set tolerance:

**`fpCompare`**[^1] | **`base`**
--------------------|-----------
`%>=%`              | `>=`
`%>>%`              | `>`
`%<=%`              | `<=`
`%<<%`              | `<`
`%==%`              | `==`
`%!=%`              | `!=`

These functions use the `base` relational operators to make comparisons, but incorporate a tolerance value (`fpCompare.tolerance`) similar to `all.equal`. The default `fpCompare.tolerance` value is `.Machine$double.eps^0.5`, set via `options`. This is the same default used in `all.equal` for numeric comparisons.

```r
# set telorance value
tol = .Machine$double.eps^0.5       # default value
options(fpCompare.tolerance = tol)

# perform comparisons
x1 <- 0.5 - 0.3
x2 <- 0.3 - 0.1
x1 == x2         # FALSE on most machines
x1 %==% x2       # TRUE everywhere
```

[^1]: The `%<<%` and `%>>%` symbols are used instead of `%<%` and `%>%` to avoid a conflict with `magrittr`'s pipe operator (`%>%`).

\newpage

# Installation

## From CRAN

```r
install.packages("fpCompare")
```

## From GitHub

```r
library(devtools)
install_github("PredictiveEcology/fpCompare")
```

# Bug Reports

[https://github.com/PredictiveEcology/fpCompare/issues](https://github.com/PredictiveEcology/fpCompare/issues)

# References
